apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: auth
  labels:
    app: auth
spec:
  type: NodePort
  metadata:
    labels:
      app: auth
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
    - name: internal-grpc
      port: 8082
      targetPort: 8082
  selector:
    app: auth
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - auth
  selector:
    matchLabels:
      app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: registry.brotherlogic-backend.com/brotherlogic/auth:0.8.0 # {"$imagepolicy": "flux-system:auth"}
          ports:
            - containerPort: 8080
          env:
            - name: USER_PASS
              valueFrom:
                secretKeyRef:
                  name: user
                  key: user_pass
      imagePullSecrets:
        - name: regcred
